# Substitua o texto abaixo pelo link inteiro que você copiou do Neon
spring.datasource.url=jdbc:postgresql://ep-damp-queen-amv696r1-pooler.c-5.us-east-1.aws.neon.tech/neondb?user=neondb_owner&password=npg_vYsVkR74Ceou&sslmode=require

# Configurações para o Spring Boot conversar com o PostgreSQL direitinho
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true